# Site settings
author: Kelly Hesterly
title: !(very_good_code)
header-img: img/home-bg.png
email: kelly.hesterly@gmail.com
copyright_name: Kelly Hesterly
description: > # this means to ignore newlines until "baseurl:"
  !(vgc)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kellyhesterly

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
